name: Sync Components types
on:
  schedule:
    - cron: '0 0 * * 6'
    

jobs:
  sync-components-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout taro
        uses: actions/checkout@v3
        with:
          repository: NervJS/taro
          fetch-depth: 1
          path: .taro
      - run : |
          cp .taro/packages/taro-components/types/* packages/taro-components/types
          cp .taro/packages/taro/types/* packages/taro/types
          rm -rf .taro

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "refactor(types): sync components types"
          title: "refactor(types): sync components types"
          body: "sync components types"
          labels: |
            A-typings
            A-components
          
